### ISSUE TITLE
DeepCell kiosk wrapper scripts has redundancies

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/kiosk-console#185]
The command to install the DeepCell kiosk wrapper script has redundancies and is sub-optimal in execution. Any kiosk docker image can be run and the `-e DOCKER_TAG` value will overwrite the given tag. To limit redundancy and possible confusion, the wrapper should parse out the desired tag and pass it in as the appropriate value.

**Comment by MekWarrior** [comment]
This redundancy is exacerbated by the fact that several ENV variables may need to be used. For instance, in addition to ```-e DOCKER_TAG```, ```-e DOCKER_IMAGE``` should also be used if the desired behavior is to launch 2 kiosks on the same machine. Additionally, launching 2 kiosks on one machine requires 2 different docker images even though the Dockerfile may be identical (the container name is derived directly from the DOCKER_IMAGE environment variable as discussed in #235).

It may be possible to override these variable names in the Dockerfile, but it doesn't appear that Docker currently makes image names and tags available from within the build process at run time.

**Comment by willgraf** [comment]
Maybe we can use `NAME` as an input?

https://github.com/cloudposse/geodesic/blob/6d018ebb0aadf8fe9375451db6dbc989e8662021/rootfs/templates/wrapper#L269

**Comment by willgraf** [comment]
Closing this issue as there is nothing to do.

Unfortunately, the [wrapper script](https://github.com/cloudposse/geodesic/blob/master/rootfs/templates/wrapper) we inherit from `cloudposse/geodesic` requires us to pass in the docker tag both as an environment variable and in the actual image name argument. If a future release of geodesic allows this to be read from the actual docker image tag rather than from the environment variable, this issue will be reopened and worked on.
