### ISSUE TITLE
"Cluster created" screen shows even if there were helm deployment issues.

### ISSUE THREAD

**Issue by MekWarrior** [vanvalenlab/kiosk-console#349]
**Describe the bug**
During a cluster creation, my `ingress` pod failed to deploy during the `make helmfile/create/all` command due to a downtime issue with the quay.io image registry. This caused `CLUSTER_IP` to be unset. However, the "Cluster Created" message showed on my screen indicating a successful deployment. We retry each deployment up to 3 times, but if it fails after the 3rd, we just move on and lose track of the fact that it failed.

These errors can be caused by several issues, but we encountered it when a 3rd party image registry experienced downtime. This caused the ingress pod sync failures and a subsequent cluster IP availability failure. 

**To Reproduce**
1. Run Kiosk Creation
2. Encounter a 3rd party availability issue (misspell the image registry path of ingress)
3. See "Cluster Created" but be unable to upload an image for prediction.

**Expected behavior**
To be able to use the cluster as expected upon receipt of a successful cluster creation message.

**Additional context**
We should include a check that properly identifies a malfunctioning cluster and alerts the user. A simple but incomplete fix would be to check for an available cluster IP, and, if there is none, alert the user that they have encountered an error that requires destruction and re-creation of the cluster. A more complete solution would be to check for a set of "base pods" required for basic kiosk functionality and to check their statuses before notifying the user that the cluster has created successfully. This message could be used to provide information to the user in the event that some failure has occurred.

**Comment by willgraf** [comment]
During `make create` if any of the tasks fails, the "Cluster Creation Failed" screen should be displayed. However, if one of the tasks silently fails without raising an error then the task will not actually fail and the creation task will continue, ultimately resulting in a "Success" screen.

If any of the tasks actually fails, the "Cluster Creation Failed" screen should be displayed.

---

While there are a few tasks that prevent errors from stopping them, they are mostly creating something that may or may not exist, and prevents an error if it already exists. However, it looks like the `helmfile/create/all` task (which calls the `gke-helmfile-deployment.sh` script) is the biggest risk, as it will fail to deploy a chart after 3 attempts, and then move on without raising an error.

I think an ideal solution would be to continue to move on but in the "Success" screen inform the user of the helm charts that did not deploy, perhaps suggest the helmfile command to redeploy them. Since the task is almost the last task in during creation, maybe the script itself can `echo` the failed deployments and the potential reinstall commands at the end.

**Comment by willgraf** [comment]
Closed by #404, which logs all failed helmfile deployments and informs the user that helmfile deployment hit errors, and includes instructions on how the user can redeploy failed deployments.
